### ISSUE TITLE
Publishing does not work.

### ISSUE THREAD

**Issue by alexandredepape** [fregante/chrome-webstore-upload#73]
<img width="1055" alt="Screenshot 2023-12-12 at 20 26 46" src="https://github.com/fregante/chrome-webstore-upload-cli/assets/25705704/89f8836d-79bf-4275-9f5d-c17870154dc8">

Despite a successful message, on https://chrome.google.com/u/1/webstore/devconsole/, my package is nor published, nor uploaded.

I have this error message when installing in github action:

<img width="1088" alt="Screenshot 2023-12-12 at 20 34 12" src="https://github.com/fregante/chrome-webstore-upload/assets/25705704/db65e5f9-0cb7-4dde-bbb3-39cb7c198764">

Would you suggest to try with node 20 ?

Here is my dev console:

<img width="1487" alt="Screenshot 2023-12-12 at 20 40 53" src="https://github.com/fregante/chrome-webstore-upload/assets/25705704/2c4ebfb8-6848-4445-ad4c-acbdedb37db5">

and here is me logging my manifest.json before zipping:

<img width="1054" alt="Screenshot 2023-12-12 at 20 39 10" src="https://github.com/fregante/chrome-webstore-upload/assets/25705704/598f76f5-ab17-4c41-a62b-54934f8513a1">

Here is my workflow:
```yml
name: Publish to Chrome Web Store

on:
  push:
    branches:
      - main

jobs:
  build-chrome-extension:
    name: Build Chrome extension artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build with Yarn
        run: yarn run prod

      - name: touch manifest.json
        run: cat production/manifest.json

      - name: Build
        run: |-
          # fill in your build steps here...
          # we archive the dist folder and include SHA commit as the last step
          zip -r chrome-extension-${{ github.sha }}.zip production

      - name: Archive chrome-extension artifact
        uses: actions/upload-artifact@v3
        with:
          name: chrome-extension-${{ github.sha }}
          path: chrome-extension-${{ github.sha }}.zip
  upload-extension:
    name: Upload extension
    runs-on: ubuntu-latest
    needs: build-chrome-extension

    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 18

      - name: Download bundle artifact
        uses: actions/download-artifact@v3
        with:
          name: chrome-extension-${{ github.sha }}

      - name: ls
        run: ls -la

      - name: Install webstore cli
        run: npm install -g chrome-webstore-upload-cli

      - name: Upload step
        run: chrome-webstore-upload publish --source chrome-extension-${{ github.sha }}.zip --extension-id hbghjfaenddmdpbkobgdcgkmcdcdjjko --client-id ${{ secrets.CLIENT }} --client-secret ${{ secrets.SECRET }} --refresh-token ${{ secrets.TOKEN }}
```

Thanks in advance.

**Comment by alexandredepape** [comment]
For those with the same problem as I do, just replace the upload step with this step that uses another package:

```yml
- name: Upload to Chrome Web Store
  uses: mobilefirstllc/cws-publish@latest
  with:
    action: 'publish'  # one of: upload, publish, testers
    client_id: ${{ secrets.CLIENT }}
    client_secret: ${{ secrets.SECRET }}
    refresh_token: ${{ secrets.TOKEN }}
    extension_id: hbghjfaenddmdpbkobgdcgkmcdcdjjko
    zip_file: chrome-extension-${{ github.sha }}.zip
```

From https://github.com/MobileFirstLLC/cws-publish

Works like a charm now.
